### ISSUE TITLE
Urgent

### ISSUE THREAD

**Issue by delphiy** [james7132/GTCourseWork#1]
Hi,
From spambase dataset , how I can calculate the following features
capital_run_length_average: continuous.
capital_run_length_longest: continuous.
capital_run_length_total:   continuous.

dataset from this link:
https://archive.ics.uci.edu/ml/datasets/Spambase?usg=ALkJrhje86fRKp9vz3s6tWiDpqjKaR_o3g

**Comment by james7132** [comment]
I'm not at liberty to discuss how to use any of the code written in this repo works. This is mostly a personal backup of schoolwork, not a guide on how to solve the problems for your particular course. I assume the problems that are presented to you in class may have been changed since my time at GT, which I cannot guarantee if the code or information in this repo is adequate at solving.

Good luck with the rest of your time at GT.
